// Generated by CoffeeScript 1.6.2
(function() {
  window.AppRouter = Backbone.Router.extend({
    routes: {
      "": "renderHome",
      "?:querystring": "renderHome",
      "*actions": "renderPage",
      "*actions?:querystring": "renderPage"
    },
    initialize: function() {
      var fragment, rootLength;

      window.app_view = new AppView();
      Backbone.history.start({
        pushState: Modernizr.history,
        silent: true,
        root: "/jornadas/" 
      });
      if (!Modernizr.history) {
        rootLength = Backbone.history.options.root.length;
        fragment = window.location.pathname.substr(rootLength);
        Backbone.history.loadUrl(fragment, {
          trigger: true
        });
        app_view.pageIdToBody(fragment.replace("/", ""));
      } else {
        Backbone.history.loadUrl(Backbone.history.getFragment());
        app_view.pageIdToBody(Backbone.history.fragment.replace("/", ""));
      }
      return this.setActiveMenu();
    }, 
    setActiveMenu: function() {
      var fragment;

      if (Backbone.history.fragment) {
        fragment = Backbone.history.fragment;
      }
      return app_view.activateMenu(fragment);
    },
    renderHome: function() {
      debugger;      return window.homeView = new HomeView();
    },
    renderPage: function() {
      debugger;      return window.pageView = new PageView();
    }
  });

  $(document).ready(function() {
    debugger;    return window.app_router = new AppRouter();
  });

}).call(this);
